---
title: "Week9"
author: "Zach Schroeder"
date: "5/28/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lme4)
library(brms)
```

```{r}
nurses <- read_csv(here::here("data", "nurses.csv"))
m1 <- lmer(stress ~ wardtype*experien + (experien|wardid),
           data = nurses)
m2 <- lmer(stress ~ hospsize + experien*wardtype +(experien|wardid) + (experien|hospital),
            data = nurses)
m3 <- lmer(stress ~ expcon + experien + age + (experien||wardid) + (experien||hospital),
           data = nurses)
m4 <- lmer(stress ~ expcon + wardtype + hospsize*experien + age + (experian|wardtid) + (experian|hospital), data = nurses)


m5 <- lmer(ln(expcon) ~ (age|wardid) + hospital, data = nurses)
m6 <- lmer(expcon ~ wardtype + age*gender + (age|wardid) + (age|hospital) + hospsize), data = nurses)

m8 <- glmer(expcon ~ age + gender + experien*wardtype +experien*hospsize + (experien|wardid) + (experien|hospital),
            data = nurses,
            family = binomial(link = "logit"))
```

```{r}
library(tidyverse)
blm <- read_rds(here::here("data", "blm_sentiment.Rds"))
blm
```
Unnesting hashtags
```{r}
blm %>% 
  unnest(hashtags) %>% 
  count(hashtags, sort = TRUE) # %>%

# PULL FEATURES FROM HASHTAGS

blm <- blm %>% 
  rowwise() %>% 
  mutate(n_hashtags = length(hashtags)) %>% 
  ungroup() 
blm %>% 
  select(user_id, n_hashtags)

# DUMMY CODES FOR ANTIFA HASHTAGS

blm <- blm %>% 
  rowwise() %>% 
  mutate(has_antifa_hashtag = any(
    grepl("antifa", tolower(hashtags))
    )
  ) %>% 
  ungroup() 
blm %>% 
  count(has_antifa_hashtag)
```

Make BLM followers_count normal
```{r}
ggplot(blm, aes(followers_count)) +
  geom_histogram()
blm <- blm %>% 
  mutate(
    fc_normal = log(followers_count)
  )
ggplot(blm, aes(fc_normal)) +
  geom_histogram()
```

Person-variance
```{r}
library(lme4)
m0_ml <- glmer(is_positive_sentiment ~ 1 + (1|user_id),
               data = blm,
               family = binomial(link = "logit"))
arm::display(m0_ml)
```


```{r}
library(brms)
m0_b <- brm(is_positive_sentiment ~ 1 + (1|user_id),
               data = blm,
               family = bernoulli(link = "logit"),
               cores = 4)
summary(m0_b)
pp_check(m0_b, type = "bars")
plot(m0_b)
library(insight)
m0_posterior <- get_parameters(m0_b)
head(m0_posterior)
sum(m0_posterior$b_Intercept < -0.5) / nrow(m0_posterior)
```

Plotting person estimates
```{r}
library(tidybayes)
get_variables(m0_b)
```

```{r}
m0_id_re <- gather_draws(m0_b, r_user_id[id, term])
m0_id_re
```

```{r}
id_qtiles <- m0_id_re %>% 
  group_by(id) %>% 
  summarize(
    probs = c("median", "lower", "upper"),
    qtiles = quantile(.value,probs = c(0.5, 0.025, 0.975))
  ) %>% 
  ungroup() 
id_qtiles
```

```{r}
id_qtiles <- id_qtiles %>% 
  pivot_wider(names_from = "probs",
              values_from = "qtiles") %>% 
  mutate(id = fct_reorder(factor(id), median))
id_qtiles
```


```{r}
ggplot(id_qtiles, aes(median, id)) +
  geom_linerange(aes(xmin = lower, xmax = upper),
                 alpha = 0.01) +
  geom_point(color = "#1DA1F2") +
  theme(axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor = element_blank())
```

```{r}
ggplot(id_qtiles, aes(median, id)) +
  geom_linerange(aes(xmin = lower, xmax = upper),
                 alpha = 0.01) +
  geom_point(color = "#1DA1F2") +
  theme(axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor = element_blank())
```

```{r extending model}
m1_b <- brm(is_positive_sentiment ~ trump_in_description + 
              has_antifa_hashtag + log(favorite_count + 1) +
              (1|user_id),
            data = blm,
            family = bernoulli(link = "logit"),
            cores = 4,
            backend = "cmdstanr")
```

# See slides for cool plots
